const fs = require('node:fs');
const assert = require('node:assert/strict');
const vm = require('node:vm');
const { stripTypeScriptTypes } = require('node:module');
const context = { exports: {} };
const billing = fs.readFileSync('src/lib/billing.ts', 'utf8').replace(/^import.*$/m, '').replaceAll('export function', 'function');
vm.runInNewContext(stripTypeScriptTypes(billing) + '\nexports.pay = recordBillPayment; exports.reconcile = reconcileBillPayments;', context);
const app = fs.readFileSync('src/App.tsx', 'utf8');
const paymentLabel = app.slice(app.indexOf('function billPaymentLabel'), app.indexOf('function Bills('));
vm.runInNewContext('const shortDate = new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" });' + stripTypeScriptTypes(paymentLabel) + '\nexports.paymentLabel = billPaymentLabel;', context);
assert.equal(context.exports.paymentLabel({ dueDate: '2026-10-05', paymentTransactionId: 'chatgpt' }, [{ id: 'chatgpt', date: '2026-10-03' }]), 'Paid Oct 3', 'Paid date must come from the payment, not the bill due date');
assert.equal(context.exports.paymentLabel({ paid: true, dueDate: '2026-10-05' }, []), 'Paid · date not linked');
const balances = app.slice(app.indexOf('function calculateAccountBalances'), app.indexOf('function greeting'));
vm.runInNewContext('const monthKey = (date) => date.slice(0,7); const transactionKind = (item) => item.type || (item.amount < 0 ? "expense" : "income"); const transactionAccount = (item) => item.account || "checking";' + stripTypeScriptTypes(balances) + '\nexports.balances = calculateAccountBalances;', context);
const bill = { id: 'rent', name: 'Rent', amount: 100, dueDate: '2026-10-04', paid: false, category: 'Housing' };
const original = { bills: [bill], transactions: [], checkingStartingBalance: 1000, savingsStartingBalance: 500, balanceStartMonth: '2026-10' };
const payment = { id: 'bill-payment-rent-2026-10-04', amount: -100, type: 'expense', account: 'checking', date: '2026-10-04' };
const paid = context.exports.pay(original, bill.id, payment);
assert.equal(paid.transactions.length, 1);
assert.equal(paid.bills[0].paymentTransactionId, payment.id);
assert.equal(paid.bills[0].paid, true);
assert.equal(context.exports.balances(paid).checking, 900);
assert.equal(context.exports.balances(paid).savings, 500);
assert.equal(context.exports.pay(paid, bill.id, payment).transactions.length, 1, 'Repeat payment must not duplicate the expense');
const linked = context.exports.pay({ ...original, transactions: [payment] }, bill.id, payment);
assert.equal(linked.transactions.length, 1, 'Linking an existing payment must not add an expense');
assert.equal(context.exports.balances(linked).checking, 900);
assert.equal(1000 + 500 - 100, 900 + 500, 'Available funds must not subtract the reserved bill again after payment');
const deleted = context.exports.reconcile({ ...paid, transactions: [] });
assert.equal(deleted.bills[0].paid, false, 'Removing a payment reopens the bill');
assert.equal(context.exports.balances(deleted).checking, 1000);
assert.throws(() => context.exports.pay(original, bill.id, { ...payment, type: 'transfer' }));
assert.throws(() => context.exports.pay(original, bill.id, { ...payment, billId: 'other' }));
const store = fs.readFileSync('src/lib/data-store.ts', 'utf8');
const mergeSource = store.slice(store.indexOf('export function mergeHouseholdChanges'), store.indexOf('const firebaseConfig'));
vm.runInNewContext(stripTypeScriptTypes(mergeSource.replace('export function', 'function')) + '\nexports.merge = mergeHouseholdChanges;', context);
const concurrentDeletion = context.exports.merge({ ...original, transactions: [payment] }, original, paid);
assert.equal(concurrentDeletion.bills[0].paid, false, 'Concurrent deletion must reopen the cloud bill too');
console.log('Billing checks passed: create once, existing link, correct balances, no double reserve, deletion reopening, invalid link rejection.');
