const fs = require('node:fs');
const assert = require('node:assert/strict');
const vm = require('node:vm');
const { stripTypeScriptTypes } = require('node:module');
const context = { exports: {} };
const billing = fs.readFileSync('src/lib/billing.ts', 'utf8').replace(/^import.*$/m, '').replaceAll('export function', 'function');
vm.runInNewContext(stripTypeScriptTypes(billing) + '\nexports.pay = recordBillPayment; exports.reconcile = reconcileBillPayments;', context);
const app = fs.readFileSync('src/App.tsx', 'utf8');
const calendarHelper = app.slice(app.indexOf('const daysUntil'), app.indexOf('const monthKey'));
vm.runInNewContext('const todayISO = () => "2026-10-04";' + stripTypeScriptTypes(calendarHelper) + '\nexports.daysUntil = daysUntil;', context);
assert.equal(context.exports.daysUntil('2026-11-04'),31,'Bill planning must count calendar days across the DST boundary');
const paymentLabel = app.slice(app.indexOf('function billPaymentLabel'), app.indexOf('function Bills('));
vm.runInNewContext('const shortDate = new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" });' + stripTypeScriptTypes(paymentLabel) + '\nexports.paymentLabel = billPaymentLabel;', context);
assert.equal(context.exports.paymentLabel({ dueDate: '2026-10-05', paymentTransactionId: 'chatgpt' }, [{ id: 'chatgpt', date: '2026-10-03' }]), 'Paid Oct 3', 'Paid date must come from the payment, not the bill due date');
assert.equal(context.exports.paymentLabel({ paid: true, dueDate: '2026-10-05' }, []), 'Paid · date not linked');
const balances = app.slice(app.indexOf('function calculateAccountBalances'), app.indexOf('function greeting'));
vm.runInNewContext('const monthKey = (date) => date.slice(0,7); const transactionKind = (item) => item.type || (item.amount < 0 ? "expense" : "income"); const transactionAccount = (item) => item.account || "checking";' + stripTypeScriptTypes(balances) + '\nexports.balances = calculateAccountBalances;', context);
const bill = { id: 'rent', name: 'Rent', amount: 100, dueDate: '2026-10-04', paid: false, category: 'Housing' };
const original = { bills: [bill], transactions: [], checkingStartingBalance: 1000, savingsStartingBalance: 500, balanceStartMonth: '2026-10' };
const payment = { id: 'bill-payment-rent-2026-10-04', amount: -100, type: 'expense', account: 'checking', date: '2026-10-04' };
const paid = context.exports.pay(original, bill.id, payment);
assert.equal(paid.transactions.length, 1);
assert.equal(paid.bills[0].paymentTransactionId, payment.id);
assert.equal(paid.bills[0].paid, true);
assert.equal(context.exports.balances(paid).checking, 900);
assert.equal(context.exports.balances(paid).savings, 500);
assert.equal(context.exports.pay(paid, bill.id, payment).transactions.length, 1, 'Repeat payment must not duplicate the expense');
const linked = context.exports.pay({ ...original, transactions: [payment] }, bill.id, payment);
assert.equal(linked.transactions.length, 1, 'Linking an existing payment must not add an expense');
assert.equal(context.exports.balances(linked).checking, 900);
assert.equal(1000 + 500 - 100, 900 + 500, 'Available funds must not subtract the reserved bill again after payment');
const deleted = context.exports.reconcile({ ...paid, transactions: [] });
assert.equal(deleted.bills[0].paid, false, 'Removing a payment reopens the bill');
assert.equal(context.exports.balances(deleted).checking, 1000);
assert.throws(() => context.exports.pay(original, bill.id, { ...payment, type: 'transfer' }));
assert.throws(() => context.exports.pay(original, bill.id, { ...payment, billId: 'other' }));
const store = fs.readFileSync('src/lib/data-store.ts', 'utf8');
const mergeSource = store.slice(store.indexOf('export function mergeHouseholdChanges'), store.indexOf('const firebaseConfig'));
vm.runInNewContext(stripTypeScriptTypes(mergeSource.replace('export function', 'function')) + '\nexports.merge = mergeHouseholdChanges;', context);
const concurrentDeletion = context.exports.merge({ ...original, transactions: [payment] }, original, paid);
assert.equal(concurrentDeletion.bills[0].paid, false, 'Concurrent deletion must reopen the cloud bill too');
console.log('Billing checks passed: create once, existing link, correct balances, no double reserve, deletion reopening, invalid link rejection.');
vm.runInNewContext('exports.nextBillDate = nextBillDate; exports.prepare = prepareNextBillCycles;', context);
const recurring = { ...bill, dueDate:'2026-01-31', recurrence:'monthly', paid:true };
let cycles = context.exports.prepare({ ...original, bills:[recurring] });
assert.equal(cycles.bills[1].dueDate,'2026-02-28');
assert.equal(cycles.transactions.length,0,'Scheduling must never create a financial transaction');
assert.equal(context.exports.prepare(cycles).bills.length,2,'Multiple devices must not create duplicate cycles');
cycles = context.exports.prepare({...cycles,bills:cycles.bills.map(item=>({...item,paid:true}))});
assert.equal(cycles.bills[2].dueDate,'2026-03-31','Month-end anchor must survive February');
assert.equal(context.exports.nextBillDate({...bill,dueDate:'2024-02-29',recurrence:'yearly'}),'2025-02-28');
assert.equal(context.exports.nextBillDate({...bill,dueDate:'2026-12-29',recurrence:'weekly'}),'2027-01-05');
const removedCycle = {...cycles,bills:cycles.bills.slice(0,2),recovery:[{id:'deleted',kind:'bill',action:'deleted',record:cycles.bills[2]}]};
assert.equal(context.exports.prepare(removedCycle).bills.length,2,'Deleted future occurrence must not regenerate');
const recoveryCode = fs.readFileSync('src/lib/recovery.ts','utf8').replace(/^import.*$/m,'').replaceAll('export function','function');
context.crypto = require('node:crypto').webcrypto;
vm.runInNewContext(stripTypeScriptTypes(recoveryCode)+'\nexports.keep = keepRecovery; exports.restore = recoverRecord;',context);
const trashed = context.exports.keep(deleted,'transaction','deleted',paid.transactions[0]);
const restored = context.exports.reconcile(context.exports.restore(trashed,trashed.recovery[0].id));
assert.equal(restored.transactions.length,1);
assert.equal(restored.bills[0].paid,true,'Restoring a linked payment must clear its reservation again');
assert.equal(context.exports.balances(restored).checking,900);
const oldBillRevision = context.exports.keep(paid,'bill','edited',bill);
const restoredBill = context.exports.reconcile(context.exports.restore(oldBillRevision,oldBillRevision.recovery[0].id));
assert.equal(restoredBill.bills[0].paid,true,'Restoring bill details must not reserve a payment that remains linked');
const recoverBase = {...original,recovery:[]};
const r1 = context.exports.keep(recoverBase,'transaction','deleted',payment);
const r2 = context.exports.keep(recoverBase,'bill','deleted',bill);
assert.equal(context.exports.merge(recoverBase,r1,r2).recovery.length,2,'Concurrent recovery histories must merge');
console.log('Recurring/recovery checks passed: anchors, duplicate prevention, deleted-cycle suppression, restore balances, cloud history merge.');
const toolsSource = fs.readFileSync('src/HouseholdTools.tsx','utf8');
const summarySource = toolsSource.slice(toolsSource.indexOf('export function MonthlySummary'),toolsSource.indexOf('export function RecoveryPanel'));
const summaryBody = summarySource.slice(summarySource.indexOf('  const [year'),summarySource.indexOf('  return <section'));
vm.runInNewContext('function kind(item) { return item.type || (item.amount < 0 ? "expense" : "income"); } function summary(transactions, month) {'+stripTypeScriptTypes(summaryBody)+'return {income, spending, savings, byCategory};}\nexports.summary = summary;',context);
const summaryRows = [{date:'2026-10-01',amount:1000,type:'income',account:'checking'},{date:'2026-10-02',amount:-100,type:'expense',category:'Groceries',account:'checking',status:'pending'},{date:'2026-10-03',amount:10,type:'expense',category:'Groceries',account:'checking'},{date:'2026-10-03',amount:300,type:'transfer',account:'checking',transferTo:'savings'},{date:'2026-10-03',amount:-20,type:'expense',category:'Health',account:'savings'},{date:'2026-10-03',amount:50,type:'income',account:'savings'},{date:'2026-09-01',amount:9999,type:'income'}];
const summary = context.exports.summary(summaryRows,'2026-10');
assert.equal(summary.income,1050); assert.equal(summary.spending,110); assert.equal(summary.savings,330); assert.equal(summary.byCategory.get('Groceries'),90);
const statusSource = app.slice(app.indexOf('function saveStatus'),app.indexOf('function viewTitle'));
vm.runInNewContext(stripTypeScriptTypes(statusSource)+'\nexports.saveStatus = saveStatus;',context);
assert.match(context.exports.saveStatus('offline',null),/waiting for cloud sync/);
assert.equal(context.exports.saveStatus('local',null),'Saved on this device only');
assert.equal(context.exports.saveStatus('connecting',new Date()),'Saving to cloud…');
assert.match(context.exports.saveStatus('synced',new Date()),/^Saved to cloud at /);
console.log('Summary/save-status checks passed: refunds, pending entries, transfer exclusions, savings movement, honest sync states.');
