const fs = require('node:fs');
const assert = require('node:assert/strict');
const vm = require('node:vm');
const { stripTypeScriptTypes } = require('node:module');
const source = fs.readFileSync('src/lib/data-store.ts', 'utf8');
const helper = source.slice(source.indexOf('export function mergeHouseholdChanges'), source.indexOf('const firebaseConfig'));
const context = { exports: {} };
const billing = fs.readFileSync('src/lib/billing.ts', 'utf8').replace(/^import.*$/m, '').replaceAll('export function', 'function');
vm.runInNewContext(stripTypeScriptTypes(billing), context);
vm.runInNewContext(stripTypeScriptTypes(helper.replace('export function', 'function')) + '\nexports.mergeHouseholdChanges = mergeHouseholdChanges;', context);
const merge = context.exports.mergeHouseholdChanges;
const row = (id, amount = -10) => ({ id, amount, date: '2026-10-01', description: id, createdAt: '2026-10-02T10:00:00Z' });
const data = (transactions) => ({ transactions, bills: [], displayName: 'Pat', safetyBuffer: 1000 });
const base = data([row('a')]);
const remote = { ...data([row('a'), row('partner')]), displayName: 'New name' };
const added = merge(base, data([row('a'), row('new')]), remote);
assert.deepEqual(Array.from(added.transactions, r => r.id), ['a', 'partner', 'new']);
assert.equal(added.displayName, 'New name');
const edited = merge(base, data([{ ...row('a'), notes: 'receipt', status: 'posted' }]), remote);
assert.equal(edited.transactions.find(r => r.id === 'a').notes, 'receipt');
assert.equal(edited.transactions.find(r => r.id === 'a').status, 'posted');
assert.equal(edited.transactions.length, 2);
const deleted = merge(base, data([]), remote);
assert.deepEqual(Array.from(deleted.transactions, r => r.id), ['partner']);
const unrelated = merge(base, { ...base, safetyBuffer: 500 }, data([]));
assert.equal(unrelated.transactions.length, 0, 'Unchanged stale rows must not resurrect deleted records');
const initial = merge(data([]), data([]), remote);
assert.equal(initial.transactions.length, 2, 'An empty device must preserve cloud records');
console.log('Sync merge checks passed: concurrent entries, edits/notes/status, deletions, stale rows, empty devices.');
const app = fs.readFileSync('src/App.tsx', 'utf8');
const sortSource = app.match(/const sortTransactions = [^\n]+/)[0];
vm.runInNewContext(stripTypeScriptTypes(sortSource) + '\nexports.sort = sortTransactions;', context);
const ordered = context.exports.sort([{ ...row('old'), date: '2026-10-01', createdAt: '2026-10-03T20:00:00Z' }, { ...row('new'), date: '2026-10-02', createdAt: '2026-10-02T20:00:00Z' }, { ...row('same-day'), date: '2026-10-02', createdAt: '2026-10-02T21:00:00Z' }]);
assert.deepEqual(Array.from(ordered, r => r.id), ['same-day', 'new', 'old']);
console.log('Sorting check passed: transaction date first, original submission time second.');
